apiVersion: bmc.tinkerbell.org/v1alpha1
kind: BMCJob
metadata:
  name: bmcjob-sample
spec:
  tasks:
    - powerAction:
        state: "off"
    - bootAction:
        bootDevice: "pxe"
        persistent: "false"
        efiBoot: "false"
    - powerAction:
        state: "on"
